### ISSUE TITLE
Multiple requests with one Twitter instance throws exception

### ISSUE THREAD

**Issue by ovo-6** [sh4869/twitter.dart#5]
This code:
```
final Twitter twitter = new Twitter(consumerKey, consumerSecret, accessToken, accessSecret);
Response response = await twitter.request("GET", "statuses/home_timeline.json");
Response response2 = await twitter.request("GET", "statuses/home_timeline.json");
```
Fails with:
```
E/flutter ( 3304): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 3304): NoSuchMethodError: The method 'openUrl' was called on null.
E/flutter ( 3304): Receiver: null
E/flutter ( 3304): Tried calling: openUrl("GET", Instance of '_SimpleUri')
E/flutter ( 3304): #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
E/flutter ( 3304): #1      IOClient.send (package:http/src/io_client.dart:30:36)
E/flutter ( 3304): <asynchronous suspension>
E/flutter ( 3304): #2      Client.send (package:oauth/client.dart:105:22)
E/flutter ( 3304): #3      Client.request (package:twitter/src/client.dart:34:22)
E/flutter ( 3304): #4      Twitter.request (package:twitter/twitter.dart:65:19)
```

**Comment by sh4869** [comment]
Thanks!

**Comment by JyotiDubey** [comment]
I am using version 0.5.2 of twitter client and looks like this issue still exists.
